version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTEST_2810Project
  gitServerName: rimaSCSiqa
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_gittest_2810.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GITTEST_2810Project
    version: "1.0"
- serviceName: project.siqa_gittest_2810.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GITTEST_2810Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: project.siqa_gittest_2810.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GITTEST_2810Project
    version: "1.0"
- serviceName: project.siqa_gittest_2810.integrations:deepclonetest
  packages:
  - name: SIQA_GITTEST_2810Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
